'use client'

import { ArrowLeft, Plus, Save, X } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { AppSidebar } from '@/components/app-sidebar'
import { createClient } from '@/lib/supabase/client'

export function SkillsManagerPage() {
  const supabase = useMemo(() => createClient(), [])
  const [userId,setUserId]=useState(''); const [skills,setSkills]=useState<string[]>([]); const [input,setInput]=useState(''); const [busy,setBusy]=useState(false); const [loading,setLoading]=useState(true); const [error,setError]=useState(''); const [message,setMessage]=useState('')
  useEffect(()=>{let active=true; (async()=>{const {data}=await supabase.auth.getUser();if(!data.user){window.location.assign('/auth/login');return}setUserId(data.user.id);const {data:links,error:e1}=await supabase.from('user_skills').select('skill_id').eq('user_id',data.user.id).eq('skill_type','OFFER');const {data:all,error:e2}=await supabase.from('skills').select('id,name');if(!active)return;if(e1||e2){setError((e1||e2)?.message||'Could not load skills.')}else{const map=new Map((all??[]).map(s=>[s.id,s.name]));setSkills((links??[]).map(x=>map.get(x.skill_id)).filter((x):x is string=>Boolean(x)))}setLoading(false)})();return()=>{active=false}},[supabase])
  async function addSkill(){const value=input.trim().replace(/\s+/g,' ');if(!value)return;if(skills.some(s=>s.toLowerCase()===value.toLowerCase()))return setError('That skill is already on your profile.');if(skills.length>=10)return setError('Choose up to 10 skills.');setBusy(true);setError('');setMessage('');let {data:skill}=await supabase.from('skills').select('id').eq('name_normalized',value.toLowerCase()).maybeSingle();if(!skill){const created=await supabase.from('skills').insert({name:value}).select('id').single();if(created.error){setError(created.error.message);setBusy(false);return}skill=created.data}const {error:e}=await supabase.from('user_skills').insert({user_id:userId,skill_id:skill.id,skill_type:'OFFER',proficiency:'INTERMEDIATE'});if(e)setError(e.code==='23505'?'That skill is already on your profile.':e.message);else{setSkills(prev=>[...prev,value]);setInput('');setMessage('Skill added.')}setBusy(false)}
  async function removeSkill(name:string){setBusy(true);setError('');const {data:skill}=await supabase.from('skills').select('id').eq('name_normalized',name.toLowerCase()).maybeSingle();if(skill){const {error:e}=await supabase.from('user_skills').delete().eq('user_id',userId).eq('skill_id',skill.id).eq('skill_type','OFFER');if(e)setError(e.message);else setSkills(prev=>prev.filter(s=>s!==name))}setBusy(false)}
  return <div className="app-page-shell"><AppSidebar/><main className="v1-content"><div className="v1-top"><div><a className="profile-back" href="/profile"><ArrowLeft size={15}/> Back to profile</a><p className="section-kicker" style={{marginTop:18}}>PROFILE SKILLS</p><h1>What you can teach</h1><p>Keep your V1 profile focused on the skills you can confidently share.</p></div></div><section className="v1-card v1-card-pad"><div className="v1-form"><label>Add a skill <span className="small-muted">{skills.length}/10</span><div style={{display:'flex',gap:8}}><input value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'){e.preventDefault();addSkill()}}} placeholder="e.g. React, Excel, Photography" disabled={loading||busy}/><button type="button" className="v1-button primary" onClick={addSkill} disabled={busy||!input.trim()||skills.length>=10}><Plus size={14}/> Add</button></div></label></div>{error&&<div className="explore-alert error" style={{marginTop:12}}>{error}</div>}{message&&<div className="explore-alert success" style={{marginTop:12}}>{message}</div>}<div className="public-profile-skills" style={{marginTop:20}}>{skills.length?skills.map(skill=><span className="public-profile-skill" key={skill}>{skill}<button type="button" style={{border:0,background:'transparent',padding:0,marginLeft:6,color:'inherit'}} onClick={()=>removeSkill(skill)} disabled={busy} aria-label={`Remove ${skill}`}><X size={12}/></button></span>):<span className="small-muted">No skills yet.</span>}</div></section></main></div>
}
